# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('price', models.PositiveIntegerField()),
                ('wx_title', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('content', models.CharField(max_length=1024)),
                ('attendant_count', models.PositiveIntegerField(default=0)),
                ('publish', models.PositiveSmallIntegerField(default=0)),
                ('img', models.ImageField(blank=True, null=True, upload_to=b'photos/activity')),
            ],
            options={
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('type', models.PositiveSmallIntegerField(db_index=True)),
                ('parent_id', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='HistoryOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('openid', models.CharField(blank=True, max_length=64, null=True)),
                ('member_card_number', models.CharField(blank=True, max_length=64, null=True)),
                ('type', models.PositiveSmallIntegerField(default=0)),
                ('number', models.CharField(max_length=32, unique=True)),
                ('contact', models.CharField(max_length=64)),
                ('telephone', models.CharField(max_length=20)),
                ('note', models.CharField(max_length=128, null=True)),
                ('terms_of_payment', models.PositiveSmallIntegerField(default=0)),
                ('money', models.PositiveIntegerField()),
                ('prepay_id', models.CharField(max_length=64, null=True)),
                ('is_payed', models.BooleanField(default=False)),
                ('time', models.DateTimeField()),
                ('status', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'history_order',
            },
        ),
        migrations.CreateModel(
            name='HistoryPlaceOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('hour', models.PositiveSmallIntegerField()),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_manage_plat.HistoryOrder')),
            ],
            options={
                'ordering': ['day', 'hour'],
                'db_table': 'history_place_order',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operator_name', models.CharField(max_length=64)),
                ('operator_role', models.CharField(max_length=32)),
                ('type', models.PositiveSmallIntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('desc', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'log',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('telephone', models.CharField(max_length=20)),
                ('is_full_member', models.BooleanField()),
                ('point', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.PositiveSmallIntegerField(default=0)),
                ('number', models.CharField(max_length=32, unique=True)),
                ('contact', models.CharField(max_length=64)),
                ('openid', models.CharField(blank=True, max_length=64, null=True)),
                ('member_card_number', models.CharField(blank=True, max_length=64, null=True)),
                ('telephone', models.CharField(max_length=20)),
                ('terms_of_payment', models.PositiveSmallIntegerField(default=0)),
                ('money', models.PositiveIntegerField()),
                ('note', models.CharField(max_length=128, null=True)),
                ('prepay_id', models.CharField(max_length=64, null=True)),
                ('time', models.DateTimeField()),
                ('is_payed', models.BooleanField(default=False)),
                ('ext', models.CharField(blank=True, max_length=512, null=True)),
                ('parent_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_manage_plat.Order')),
            ],
            options={
                'ordering': ['-time'],
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('note', models.CharField(max_length=128, null=True)),
                ('time_unit', models.PositiveSmallIntegerField(default=60)),
                ('business_time', models.CharField(max_length=512, null=True)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'place',
            },
        ),
        migrations.CreateModel(
            name='PlaceOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('hour', models.PositiveSmallIntegerField()),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_manage_plat.Order')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_manage_plat.Place')),
            ],
            options={
                'ordering': ['day', 'hour'],
                'db_table': 'place_order',
            },
        ),
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'place_type',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weekday', models.PositiveSmallIntegerField()),
                ('hour', models.PositiveSmallIntegerField()),
                ('price', models.PositiveSmallIntegerField()),
                ('place_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_manage_plat.PlaceType')),
            ],
            options={
                'ordering': ['hour'],
                'db_table': 'price',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'sport',
            },
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('contact', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=256)),
                ('telephone', models.CharField(max_length=20)),
                ('facility', models.CharField(max_length=256)),
                ('img', models.ImageField(blank=True, null=True, upload_to=b'photos/stadium')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_manage_plat.Area')),
            ],
            options={
                'db_table': 'stadium',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('contact', models.CharField(max_length=64)),
                ('cellphone', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'tenant',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('passwd', models.CharField(max_length=64)),
                ('telephone', models.CharField(max_length=20, null=True)),
                ('role', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
                ('expire_time', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_manage_plat.Tenant')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserStadium',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_manage_plat.Stadium')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_manage_plat.User')),
            ],
            options={
                'db_table': 'user_stadium',
            },
        ),
        migrations.AddField(
            model_name='stadium',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant_manage_plat.Tenant'),
        ),
        migrations.AddField(
            model_name='price',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_manage_plat.Sport'),
        ),
        migrations.AddField(
            model_name='price',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_manage_plat.Stadium'),
        ),
        migrations.AddField(
            model_name='placetype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_manage_plat.Tenant'),
        ),
        migrations.AddField(
            model_name='place',
            name='place_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_manage_plat.PlaceType'),
        ),
        migrations.AddField(
            model_name='place',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_manage_plat.Sport'),
        ),
        migrations.AddField(
            model_name='place',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_manage_plat.Stadium'),
        ),
        migrations.AddField(
            model_name='order',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_manage_plat.Stadium'),
        ),
        migrations.AddField(
            model_name='historyplaceorder',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_manage_plat.Place'),
        ),
        migrations.AddField(
            model_name='historyorder',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_manage_plat.Stadium'),
        ),
        migrations.AddField(
            model_name='activity',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_manage_plat.Stadium'),
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together=set([('place_type', 'sport', 'stadium', 'name')]),
        ),
    ]
