# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_manage_plat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='appid',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='key',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='mch_id',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='secret',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
