# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_manage_plat', '0004_remove_tenant_wx_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityApplicant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('telephone', models.CharField(max_length=20)),
                ('checked', models.SmallIntegerField(default=0)),
                ('prepay_id', models.CharField(max_length=64, null=True)),
                ('time', models.DateTimeField()),
                ('is_payed', models.BooleanField(default=False)),
                ('money', models.PositiveIntegerField()),
                ('terms_of_payment', models.PositiveSmallIntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_manage_plat.Activity')),
            ],
        ),
    ]
