# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_manage_plat', '0005_activityapplicant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityapplicant',
            old_name='time',
            new_name='apply_time',
        ),
    ]
