# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_manage_plat', '0006_auto_20160204_2117'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activityapplicant',
            table='activity_applicant',
        ),
    ]
