# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_manage_plat', '0007_auto_20160204_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityapplicant',
            name='apply_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
