# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_manage_plat', '0009_remove_activityapplicant_money'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='appid',
            new_name='openid',
        ),
        #migrations.AddField(
        #    model_name='activityapplicant',
        #    name='number',
        #    field=models.CharField(null=True, max_length=32, unique=True),
        #    preserve_default=False,
        #),
        #migrations.AddField(
        #    model_name='activityapplicant',
        #    name='openid',
        #    field=models.CharField(blank=True, max_length=64, null=True),
        #),
    ]
