# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_manage_plat', '0010_auto_20160204_2208'),
    ]

    operations = [
        #migrations.AlterField(
        #    model_name='activityapplicant',
        #    name='number',
        #    field=models.CharField(max_length=32, null=True, unique=True),
        #),
    ]
