# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_manage_plat', '0011_auto_20160204_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='openid',
            new_name='appid',
        ),
    ]
