# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-28 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_manage_plat', '0012_auto_20160204_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeixinUser',
            fields=[
                ('openid', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('phone', models.CharField(default=b'', max_length=20, null=True)),
                ('avatar', models.CharField(default=b'/media/photos/users/wx_test.jpg', max_length=164)),
                ('balance', models.PositiveSmallIntegerField(default=0)),
                ('credits', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'weixin_user',
            },
        ),
    ]
